AUTO_MAPPING_RULES = {
    "occurrenceID": ["개체번호", "데이터베이스번호", "출현id", "occurrenceid", "recordid", "catalogid", "db_no", "id"],
    "basisOfRecord": ["기록유형", "basisofrecord"],
    "catalogNumber": ["표본번호", "기록번호", "catalognumber"],
    "recordedBy": ["채집자", "조사자", "recordedby", "collector"],
    "individualCount": ["개체수", "개체수량", "individualcount", "count"],
    "sex": ["성별", "sex"],
    "lifeStage": ["생애단계", "life stage", "lifestage"],
    "occurrenceStatus": ["존재여부", "occurrencestatus"],
    "occurrenceRemarks": ["비고", "관찰비고", "occurrenceremarks", "remarks"],
    "eventDate": ["관찰일", "관찰월일", "관찰일 영문", "eventdate", "observationdate", "collectiondate", "date"],
    "year": ["연도", "year"],
    "month": ["월", "month"],
    "day": ["일", "day"],
    "habitat": ["서식지", "habitat"],
    "samplingProtocol": ["조사방법", "samplingprotocol", "protocol"],
    "countryCode": ["국가코드", "countrycode", "country"],
    "stateProvince": ["시도", "시도 영문", "stateprovince", "state", "province"],
    "county": ["시군구", "시군구 영문", "county", "district"],
    "locality": ["읍면동", "읍면동 영문", "locality", "location", "site"],
    "verbatimLocality": ["상세위치", "상세위치 영문", "verbatimlocality", "detaillocation", "locationdetail"],
    "decimalLatitude": ["위도", "위도 영문", "decimallatitude", "latitude", "lat"],
    "decimalLongitude": ["경도", "경도 영문", "decimallongitude", "longitude", "lon", "lng"],
    "coordinateUncertaintyInMeters": ["좌표오차", "coordinateuncertaintyinmeters", "coordinateuncertainty"],
    "identifiedBy": ["동정자", "동정자 영문", "identifiedby", "determinavit", "identifier"],
    "dateIdentified": ["동정일", "동정년월일", "동정년월일 영문", "dateidentified", "identifieddate"],
    "identificationRemarks": ["동정비고", "identificationremarks"],
    "scientificName": ["학명", "학명 영문", "scientificname", "scientific", "sci_name", "species"],
    "vernacularName": ["국명", "국명 영문", "vernacularname", "commonname"],
    "kingdom": ["계", "kingdom"],
    "phylum": ["문", "phylum"],
    "class": ["강", "class"],
    "order": ["목", "order"],
    "family": ["과", "family"],
    "genus": ["속", "genus"],
    "taxonRank": ["분류계급", "taxonrank", "rank"],
    "scientificNameAuthorship": ["명명자", "scientificnameauthorship", "authorship"],
    "institutionCode": ["기관코드", "institutioncode"],
    "collectionCode": ["분류코드","컬렉션코드", "collectioncode"],
}
