ISO_COUNTRY_CODES = [
    "",  # Empty value allowed
    "KR", "MN", "JP", "CN", "US", "VN", "TH",
    "PH", "ID", "IN", "RU", "CA", "AU", "GB",
    "FR", "DE", "BR", "ZA"
]

GBIF_COUNTRY_OPTIONS = [
    ("KR", "South Korea"),
    ("MN", "Mongolia"),
    ("JP", "Japan"),
    ("CN", "China"),
    ("US", "United States of America"),
    ("VN", "Vietnam"),
    ("TH", "Thailand"),
    ("PH", "Philippines"),
    ("ID", "Indonesia"),
    ("IN", "India"),
    ("RU", "Russia"),
    ("CA", "Canada"),
    ("AU", "Australia"),
    ("GB", "United Kingdom of Great Britain and Northern Ireland"),
    ("FR", "France"),
    ("DE", "Germany"),
    ("BR", "Brazil"),
    ("ZA", "South Africa"),
    ("ES", "Spain"),
    ("SE", "Sweden"),
    ("FI", "Finland"),
    ("DK", "Denmark"),
    ("NL", "Netherlands"),
    ("IT", "Italy"),
    ("NO", "Norway"),
    ("MX", "Mexico"),
    ("AR", "Argentina"),
    ("CL", "Chile"),
    ("CO", "Colombia"),
    ("PE", "Peru"),
    ("NZ", "New Zealand"),
    ("MY", "Malaysia"),
    ("SG", "Singapore"),
    ("MM", "Myanmar"),
    ("LA", "Laos"),
    ("KH", "Cambodia"),
    ("NP", "Nepal"),
    ("BD", "Bangladesh"),
    ("PK", "Pakistan"),
    ("LK", "Sri Lanka"),
    ("TR", "Turkey"),
    ("IR", "Iran"),
    ("SA", "Saudi Arabia"),
    ("AE", "United Arab Emirates"),
    ("IL", "Israel"),
    ("EG", "Egypt"),
    ("KE", "Kenya"),
    ("TZ", "Tanzania"),
    ("UG", "Uganda"),
    ("ET", "Ethiopia"),
    ("MG", "Madagascar"),
    ("PT", "Portugal"),
    ("BE", "Belgium"),
    ("CH", "Switzerland"),
    ("AT", "Austria"),
    ("PL", "Poland"),
    ("CZ", "Czechia"),
    ("SK", "Slovakia"),
    ("HU", "Hungary"),
    ("RO", "Romania"),
    ("GR", "Greece"),
    ("IE", "Ireland"),
    ("IS", "Iceland"),
    ("UA", "Ukraine"),
]

GBIF_CONTINENT_OPTIONS = [
    ("AFRICA", "Africa"),
    ("ANTARCTICA", "Antarctica"),
    ("ASIA", "Asia"),
    ("EUROPE", "Europe"),
    ("NORTH_AMERICA", "North America"),
    ("OCEANIA", "Oceania"),
    ("SOUTH_AMERICA", "South America"),
]

ISO_COUNTRY_CODES = ["", *[code for code, _ in GBIF_COUNTRY_OPTIONS]]
